// Generated by TaroBase SDK Generator: 2026-07-15T16:35:00.259Z
// Edits may be overwritten by subsequent runs!
//
// IMPORTANT: When a backend endpoint reads from 2+ collections, use getMany()
// getMany() makes ONE network
// request instead of multiple. Example:
//   const [profile, settings, stats] = await getMany([
//     "profiles/" + walletAddress,
//     "settings/" + walletAddress,
//     "stats/" + walletAddress,
//   ]);
//   // Each result: { path, data, error? }

import { get, set, subscribe, setMany as tarobaseSetMany } from '@pooflabs/web';
import { getFiles, setFile } from '@pooflabs/web';
import { getMany as tarobaseGetMany } from '@pooflabs/core';
import type { GetManyResult } from '@pooflabs/core';
import { PublicKey } from '@solana/web3.js';
import { runQuery } from '@pooflabs/web'; 


// --- SDK Utilities ---

/**
 * Helper function to check if a value is a Time.Now value
 */
const isServerTimeNow = (value: any): value is TimeOperation => {
  return (
    value &&
    typeof value === "object" &&
    value.operation === "time" &&
    value.value === "now"
  );
};

/**
 * Helper function to check if a value is an Increment operation
 */
const isIncrementOperation = (value: any): value is IncrementOperation => {
  return (
    value &&
    typeof value === "object" &&
    value.operation === "increment" &&
    typeof value.value === "number"
  );
};

/**
 * Time utility for server-time values
 *
 * Use this when you want to store the current server time in a numeric field
 *
 * Example:
 * // For a schema with { createdAt: "UInt" }
 * await setPost("123", {
 *   title: "My Post",
 *   createdAt: Time.Now  // Will be stored as the server's current timestamp
 * });
 *
 * Note: Time.Now requires a UInt field. Int (signed) is rejected both offchain
 * and onchain (utils.rs InvalidTypeForTimestamp).
 */
export interface TimeOperation {
  operation: string;
  value: string;
}

/**
 * Increment utility for incrementing/decrementing numeric fields
 *
 * Use this when you want to increment or decrement a numeric field by a specific amount
 *
 * Example:
 * // For a schema with { viewCount: "UInt" } or { balance: "Int" }
 * await updatePost("123", {
 *   viewCount: Increment.by(1)  // Increments viewCount by 1
 * });
 * await updateAccount("456", {
 *   balance: Increment.by(-50)  // Decrements balance by 50
 * });
 */
export interface IncrementOperation {
  operation: string;
  value: number;
}

export type TokenName = 'USDC' | 'SOL' | 'pSOL' | 'other';
export interface TokenAmount {
  type: 'token';
  name: TokenName;
  amount: number; // User-friendly amount (e.g., 10.5 SOL)
}

/**
 * AddressType represents a Solana public key for use in request data.
 */
export interface AddressType {
  type: 'address';
  publicKey: PublicKey | string;
}

/**
 * Helper function to check if a value is a TokenAmount value
 */
const isTokenAmount = (value: any): value is TokenAmount => {
  return value && typeof value === 'object' && value.type === 'token';
};

/**
 * Helper function to check if a value is an AddressType value
 */
const isAddressType = (value: any): value is AddressType => {
    // Check for the 'address' type property and that publicKey is an instance of PublicKey
    return value && typeof value === 'object' && value.type === 'address';
};


/**
 * Transforms special values (Time.now, Token.amount, Address.publicKey) in an object
 * to the format expected by the backend before sending the request.
 * This function is recursive and handles nested objects and arrays.
 */
const transformValues = (data: any): any => {
  // Handle null or non-object/array types directly
  if (!data || typeof data !== 'object') {
    return data;
  }

  // Check for specific object types first using type guards
  if (isServerTimeNow(data)) {
    // Pass Time.Now object as is; backend interprets it
    return { operation: 'time', value: 'now' };
  } else if (isIncrementOperation(data)) {
    // Pass Increment operation as is; backend interprets it
    return { operation: 'increment', value: data.value };
  } else if (isTokenAmount(data)) {
    // Convert user-friendly amount to backend's integer format based on decimals
    const { name, amount } = data; // Safe access due to type guard
    if (name === 'USDC') {
      return Math.round(amount * 10 ** 6); // 6 decimals for USDC
    } else if (name === 'SOL' || name === 'pSOL') {
      return Math.round(amount * 10 ** 9); // 9 decimals for SOL
    } else {
      // Assume a default of 6 decimals for custom tokens
      return Math.round(amount * 10 ** 6);
    }
  } else if (isAddressType(data)) {
     // Convert AddressType to its base58 string representation for the backend
     if (typeof data.publicKey === 'string') {
      return data.publicKey;
     } else {
      return data.publicKey.toBase58(); // Safe access due to type guard
     }
  }

  // Handle arrays: recursively transform each item
  if (Array.isArray(data)) {
    // Use map with explicit typing for clarity
    return data.map((item: any) => transformValues(item));
  }

  // Handle regular objects: recursively transform each property
  // Create a new object to avoid modifying the original
  const result: Record<string, any> = {};
  for (const key in data) {
    // Use safer check for own properties
    if (Object.prototype.hasOwnProperty.call(data, key)) {
      result[key] = transformValues(data[key]);
    }
  }
  return result;
};

// --- SDK Helper Objects ---

export const Token: {
  /**
   * Creates a TokenAmount object representing a specific amount of a token.
   * @param name The name of the token (e.g., 'USDC', 'SOL', 'pSOL').
   * @param amount The user-friendly amount (e.g., 10.5 for 10.5 USDC).
   */
  amount: (name: TokenName, amount: number) => TokenAmount;
  /**
   * Converts a TokenAmount object back to its integer representation based on decimals.
   * Useful if you need the raw integer value on the client side.
   */
  convert: (amount: TokenAmount) => number;
} = {
  amount: (name: TokenName, amount: number): TokenAmount => ({
    type: 'token',
    name,
    amount,
  }),
  convert: (amount: TokenAmount): number => {
    // This logic mirrors the transformation in transformValues
    if (amount.name === 'USDC') {
      return Math.round(amount.amount * 10 ** 6);
    } else if (amount.name === 'SOL' || amount.name === 'pSOL') {
      return Math.round(amount.amount * 10 ** 9);
    }
    return Math.round(amount.amount * 10 ** 6); // Default or handle 'other'
  },
};

export const Time: {
  /**
   * Represents the server's current time. Use this value for 'UInt' fields only
   * in request data where you want the server to insert the timestamp.
   * (Onchain and offchain both require UInt — Int is rejected with InvalidTypeForTimestamp.)
   */
  Now: TimeOperation;
} = {
  Now: { operation: "time", value: "now" }
};

export const Increment: {
  /**
   * Creates an increment/decrement operation for numeric fields.
   * Use positive values to increment, negative values to decrement.
   * @param value The amount to increment (positive) or decrement (negative)
   *
   * Example:
   * // Increment a counter by 1
   * await updatePost("123", { viewCount: Increment.by(1) });
   *
   * // Decrement a balance by 50
   * await updateAccount("456", { balance: Increment.by(-50) });
   */
  by: (value: number) => IncrementOperation;
} = {
  by: (value: number): IncrementOperation => ({
    operation: "increment",
    value
  })
};

export const Address: {
  /**
   * Creates an AddressType object from a PublicKey instance or a base58 string.
   * Validates the input and throws an error if invalid.
   * Special case: 'solana' is allowed as a reserved string representing native SOL.
   * @param key A PublicKey instance, a base58 encoded public key string, or 'solana' for native SOL.
   */
  publicKey: (key: PublicKey | string) => AddressType;
} = {
  publicKey: (key: PublicKey | string): AddressType => {
    if (typeof key === 'string') {
      // Special case: 'solana' represents native SOL asset
      if (key === 'solana') {
        return {
          type: 'address',
          publicKey: 'solana',
        };
      }
      // Validate format: Solana addresses are 32-44 base58 characters
      if (key.length < 32 || key.length > 44) {
        throw new Error(`Invalid Solana address length: ${key.length}. Must be 32-44 characters.`);
      }
      const base58Regex = /^[1-9A-HJ-NP-Za-km-z]+$/;
      if (!base58Regex.test(key)) {
        throw new Error(`Invalid Solana address: contains invalid characters. Must be base58 encoded.`);
      }
      try {
        // Validate and create PublicKey from string
        const pkInstance = new PublicKey(key);
        return {
          type: 'address',
          publicKey: pkInstance,
        };
      } catch (e) {
        // Safer error handling
        const message = e instanceof Error ? e.message : String(e);
        console.error(`Invalid public key string provided: ${key}`, message);
        throw new Error(`Invalid public key string: ${key}. ${message}`);
      }
    } else if (key instanceof PublicKey) {
      return {
        type: 'address',
        publicKey: key,
      };
    } else {
      // Handle invalid input type
      throw new Error('Invalid input for Address.publicKey: Must be a PublicKey instance or a base58 string.');
    }
  },
};

// --- Common Interfaces ---
/**
 * Common metadata fields added by TaroBase to document responses.
 */
export interface TarobaseMetadata {
  id: string;
  tarobase_created_at: number; // epoch milliseconds
}

/**
 * Represents a file stored in TaroBase Storage.
 */
export interface FileItem {
  path: string; // Full path within storage
  url: string;  // Publicly accessible URL
}

/**
 * Represents a document operation for use with setMany.
 * Used by build functions to create properly typed operations.
 */
export interface DocumentOperation {
  path: string;
  document: any;
}

// --- Batch Operations ---

/**
 * Execute multiple document operations in a single batch.
 * @param operations Array of DocumentOperation objects created by build functions
 * @returns Promise resolving to the result of the batch operation
 */
export async function setMany(operations: DocumentOperation[]): Promise<any> {
  return await tarobaseSetMany(operations);
}

/**
 * Batch read multiple documents by their full paths in a single request.
 * Much faster than multiple individual get() calls — single network round trip.
 * Returns results in the same order as input paths. Max 30 paths per request.
 * Each result has { path, data, error? } — one failure doesn't break the batch.
 * 
 * ALWAYS use this instead of multiple get() calls when reading 2+ documents by path.
 * 
 * @param paths Array of full document paths (e.g., ["players/abc", "settings/abc"])
 * @example
 * const [profile, settings, stats] = await getMany([
 *   "profiles/" + walletAddress,
 *   "settings/" + walletAddress,
 *   "stats/" + walletAddress,
 * ]);
 * if (profile.data) { // use profile data }
 */
export async function getMany(paths: string[]): Promise<GetManyResult[]> {
  return await tarobaseGetMany(paths);
}

// --- Error Formatting ---

/**
 * Safely format an error for logging (avoids [object Object] in logs)
 * Handles circular references, empty messages, and non-Error objects
 * Always includes the full error object for comprehensive debugging
 */
export function formatError(error: unknown): string {
  if (error === null) return 'null';
  if (error === undefined) return 'undefined';
  if (typeof error === 'string') return error || 'Empty error string';

  // For Error instances, prepend the message for readability
  const prefix = error instanceof Error ? `${error.message?.trim() || 'No message'} | Full error: ` : '';

  try {
    // Use Object.getOwnPropertyNames to include non-enumerable properties (like Error's name, message, stack)
    const str = JSON.stringify(error, Object.getOwnPropertyNames(error), 2);
    return prefix + (str || 'Empty object');
  } catch {
    // Circular reference or other stringify error
    return prefix + 'Unserializable error';
  }
}

// --- Generated Functions by Policy Path ---

// --- Path: adminFiles/$fileId ---

/**
 * Handles AdminFiles files (Get Single File based on its ID, null if not found)
 */
export async function getAdminFiles(fileId: string): Promise<FileItem | null> {
  try {
    const rawResult = await getFiles(`adminFiles/${fileId}`);
    if (!rawResult || !Array.isArray(rawResult) || rawResult.length === 0) return null;
    return rawResult[0] as FileItem;
  } catch (error) {
    console.error(`Error getting file AdminFiles: ${formatError(error)}`);
    return null;
  }
}

/**
 * Handles AdminFiles files (Upload/Replace a File and persist it keyed by its ID) To get the file URL use the getAdminFiles function right after this one.
 * @returns A boolean indicating whether the upload succeeded (true) or failed (false). Always check this value to confirm the upload worked.
 */
export async function uploadAdminFiles(fileId: string, file: File): Promise<boolean> {
  try {
    const pathUsed = `adminFiles/${fileId}`;
    const result = await setFile(pathUsed, file);
    return !!result;
  } catch (error) {
    console.error(`Error uploading file AdminFiles: ${formatError(error)}`);
    return false;
  }
}

/**
 * Handles AdminFiles files (Delete File based on its ID)
 * @returns A boolean indicating whether the delete succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteAdminFiles(fileId: string): Promise<boolean> {
  try {
    await setFile(`adminFiles/${fileId}`, null);
    return true;
  } catch (error) {
    console.error(`Error deleting file AdminFiles: ${formatError(error)}`);
    return false;
  }
}

// --- Path: appFiles/$fileId ---

/**
 * Handles AppFiles files (Get Single File based on its ID, null if not found)
 */
export async function getAppFiles(fileId: string): Promise<FileItem | null> {
  try {
    const rawResult = await getFiles(`appFiles/${fileId}`);
    if (!rawResult || !Array.isArray(rawResult) || rawResult.length === 0) return null;
    return rawResult[0] as FileItem;
  } catch (error) {
    console.error(`Error getting file AppFiles: ${formatError(error)}`);
    return null;
  }
}

/**
 * Handles AppFiles files (Upload/Replace a File and persist it keyed by its ID) To get the file URL use the getAppFiles function right after this one.
 * @returns A boolean indicating whether the upload succeeded (true) or failed (false). Always check this value to confirm the upload worked.
 */
export async function uploadAppFiles(fileId: string, file: File): Promise<boolean> {
  try {
    const pathUsed = `appFiles/${fileId}`;
    const result = await setFile(pathUsed, file);
    return !!result;
  } catch (error) {
    console.error(`Error uploading file AppFiles: ${formatError(error)}`);
    return false;
  }
}

/**
 * Handles AppFiles files (Delete File based on its ID)
 * @returns A boolean indicating whether the delete succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteAppFiles(fileId: string): Promise<boolean> {
  try {
    await setFile(`appFiles/${fileId}`, null);
    return true;
  } catch (error) {
    console.error(`Error deleting file AppFiles: ${formatError(error)}`);
    return false;
  }
}

// --- Path: commonQueries/$queryId ---

export interface CommonQueriesRequest {

}

export interface CommonQueriesResponse {

  id: string;
  tarobase_created_at: number;
}

/**
 * 
  Read Operation Details: Anyone can use these queries: (1) Balance queries - check SOL, USDC, or any SPL token balance for any wallet address. (2) Jupiter swap quotes - get expected output amounts for token swaps via Jupiter aggregator. (3) Meteora swap quotes - get expected output amounts for Meteora dynamic bonding curve pools.
   (Get Single Item)
 */
export async function getCommonQueries(queryId: string): Promise<CommonQueriesResponse | null> {
  try {
    const result = await get(`commonQueries/${queryId}`);
    return result as CommonQueriesResponse | null;
  } catch (error) {
    console.error(`Error getting CommonQueries: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single CommonQueries document. (
  Read Operation Details: Anyone can use these queries: (1) Balance queries - check SOL, USDC, or any SPL token balance for any wallet address. (2) Jupiter swap quotes - get expected output amounts for token swaps via Jupiter aggregator. (3) Meteora swap quotes - get expected output amounts for Meteora dynamic bonding curve pools.
  )
 */
export function subscribeCommonQueries(callback: (data: CommonQueriesResponse | null) => void, queryId: string): Promise<() => Promise<void>> {
  return subscribe(`commonQueries/${queryId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as CommonQueriesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to CommonQueries at path '${`commonQueries/${queryId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many CommonQueries items from collection commonQueries
 
  Read Operation Details: Anyone can use these queries: (1) Balance queries - check SOL, USDC, or any SPL token balance for any wallet address. (2) Jupiter swap quotes - get expected output amounts for token swaps via Jupiter aggregator. (3) Meteora swap quotes - get expected output amounts for Meteora dynamic bonding curve pools.
  
 */
export async function getManyCommonQueries(filter: string = ""): Promise<CommonQueriesResponse[]> {
  try {
    const results = await get("commonQueries", { prompt: filter });
    return Array.isArray(results) ? results as CommonQueriesResponse[] : [];
  } catch (error) {
    console.error(`Error getting CommonQueries collection at path 'commonQueries': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in CommonQueries collection at commonQueries
 
  Read Operation Details: Anyone can use these queries: (1) Balance queries - check SOL, USDC, or any SPL token balance for any wallet address. (2) Jupiter swap quotes - get expected output amounts for token swaps via Jupiter aggregator. (3) Meteora swap quotes - get expected output amounts for Meteora dynamic bonding curve pools.
  
 */
export function subscribeManyCommonQueries(callback: (data: CommonQueriesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("commonQueries", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as CommonQueriesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to CommonQueries collection at path '${"commonQueries"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all CommonQueries items from collection commonQueries
 
  Read Operation Details: Anyone can use these queries: (1) Balance queries - check SOL, USDC, or any SPL token balance for any wallet address. (2) Jupiter swap quotes - get expected output amounts for token swaps via Jupiter aggregator. (3) Meteora swap quotes - get expected output amounts for Meteora dynamic bonding curve pools.
  
 */
export async function getAllCommonQueries(filter: string = ""): Promise<CommonQueriesResponse[]> {
  try {
    const results = await get("commonQueries", { prompt: filter });
    return Array.isArray(results) ? results as CommonQueriesResponse[] : [];
  } catch (error) {
    console.error(`Error getting CommonQueries collection at path 'commonQueries': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in CommonQueries collection at commonQueries
 
  Read Operation Details: Anyone can use these queries: (1) Balance queries - check SOL, USDC, or any SPL token balance for any wallet address. (2) Jupiter swap quotes - get expected output amounts for token swaps via Jupiter aggregator. (3) Meteora swap quotes - get expected output amounts for Meteora dynamic bonding curve pools.
  
 */
export function subscribeAllCommonQueries(callback: (data: CommonQueriesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("commonQueries", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as CommonQueriesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to CommonQueries collection at path '${"commonQueries"}': ${formatError(error)}`);
    }
  });
}

/** Arguments accepted by the "solBalance" query on CommonQueries. */
interface CommonQueriesSolBalanceArgs {
  walletAddress: string;
}

/**
 * Runs the "solBalance" query on CommonQueries.
 * Description: Get SOL balance for a wallet address in lamports (1 SOL = 1,000,000,000 lamports). Pass walletAddress as parameter.
 * Query Logic: @TokenPlugin.getBalance(@newData.walletAddress, @constants.SOL)
 */
export async function runSolBalanceQueryForCommonQueries(queryId: string, args: CommonQueriesSolBalanceArgs): Promise<number> {
  try {
    const result = await runQuery(`commonQueries/${queryId}`, "solBalance", args);
    return (typeof result === "bigint" ? Number(result) : Number(result ?? 0));
  } catch (error) {
    console.error(`Error running query "solBalance" on CommonQueries: ${formatError(error)}`);
    throw error;
  }
}

/** Arguments accepted by the "usdcBalance" query on CommonQueries. */
interface CommonQueriesUsdcBalanceArgs {
  walletAddress: string;
}

/**
 * Runs the "usdcBalance" query on CommonQueries.
 * Description: Get USDC balance for a wallet address in base units (1 USDC = 1,000,000 base units with 6 decimals). Pass walletAddress as parameter.
 * Query Logic: @TokenPlugin.getBalance(@newData.walletAddress, @constants.USDC)
 */
export async function runUsdcBalanceQueryForCommonQueries(queryId: string, args: CommonQueriesUsdcBalanceArgs): Promise<number> {
  try {
    const result = await runQuery(`commonQueries/${queryId}`, "usdcBalance", args);
    return (typeof result === "bigint" ? Number(result) : Number(result ?? 0));
  } catch (error) {
    console.error(`Error running query "usdcBalance" on CommonQueries: ${formatError(error)}`);
    throw error;
  }
}

/** Arguments accepted by the "tokenBalance" query on CommonQueries. */
interface CommonQueriesTokenBalanceArgs {
  walletAddress: string;
  tokenMint: string;
}

/**
 * Runs the "tokenBalance" query on CommonQueries.
 * Description: Get balance for any SPL token mint for a wallet address. Pass walletAddress and tokenMint as parameters. Returns balance in the token's smallest units based on its decimals.
 * Query Logic: @TokenPlugin.getBalance(@newData.walletAddress, @newData.tokenMint)
 */
export async function runTokenBalanceQueryForCommonQueries(queryId: string, args: CommonQueriesTokenBalanceArgs): Promise<number> {
  try {
    const result = await runQuery(`commonQueries/${queryId}`, "tokenBalance", args);
    return (typeof result === "bigint" ? Number(result) : Number(result ?? 0));
  } catch (error) {
    console.error(`Error running query "tokenBalance" on CommonQueries: ${formatError(error)}`);
    throw error;
  }
}

/** Arguments accepted by the "jupiterSwapQuote" query on CommonQueries. */
interface CommonQueriesJupiterSwapQuoteArgs {
  inputMint: string;
  outputMint: string;
  amount: string;
}

/**
 * Runs the "jupiterSwapQuote" query on CommonQueries.
 * Description: Get a Jupiter swap quote for exchanging tokens. Pass inputMint (token to sell, use @constants.SOL for native SOL), outputMint (token to buy), and amount (in smallest units like lamports). Returns the expected output amount.
 * Query Logic: @DeFiPlugin.getSwapQuote(@newData.inputMint, @newData.outputMint, @newData.amount)
 */
export async function runJupiterSwapQuoteQueryForCommonQueries(queryId: string, args: CommonQueriesJupiterSwapQuoteArgs): Promise<number> {
  try {
    const result = await runQuery(`commonQueries/${queryId}`, "jupiterSwapQuote", args);
    return (typeof result === "bigint" ? Number(result) : Number(result ?? 0));
  } catch (error) {
    console.error(`Error running query "jupiterSwapQuote" on CommonQueries: ${formatError(error)}`);
    throw error;
  }
}

/** Arguments accepted by the "meteoraSwapQuote" query on CommonQueries. */
interface CommonQueriesMeteoraSwapQuoteArgs {
  tokenMintAddress: string;
  tokenToSwapInMintAddress: string;
  tokenAmount: string;
}

/**
 * Runs the "meteoraSwapQuote" query on CommonQueries.
 * Description: Get a Meteora dynamic bonding curve swap quote. Pass tokenMintAddress (the pool's base token), tokenToSwapInMintAddress (token to swap in, use @constants.SOL for native SOL), and tokenAmount (in smallest units). Returns the expected output amount.
 * Query Logic: @DeFiPlugin.getMeteoraSwapQuote(@newData.tokenMintAddress, @newData.tokenToSwapInMintAddress, @newData.tokenAmount)
 */
export async function runMeteoraSwapQuoteQueryForCommonQueries(queryId: string, args: CommonQueriesMeteoraSwapQuoteArgs): Promise<number> {
  try {
    const result = await runQuery(`commonQueries/${queryId}`, "meteoraSwapQuote", args);
    return (typeof result === "bigint" ? Number(result) : Number(result ?? 0));
  } catch (error) {
    console.error(`Error running query "meteoraSwapQuote" on CommonQueries: ${formatError(error)}`);
    throw error;
  }
}

// --- Path: profiles/$profileId ---

export interface ProfilesRequest {
  address: AddressType;
  displayName: string;
  avatarUrl?: string;
  bio?: string;
  plan: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface ProfilesResponse {
  address: string;
  displayName: string;
  avatarUrl?: string;
  bio?: string;
  plan: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Profiles operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildProfiles(profileId: string, data: ProfilesRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `profiles/${profileId}`, document: doc };
}

/**
 * Authenticated users only. The address field must equal @user.address (users create only their own profile). createdAt is Unix seconds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setProfiles(profileId: string, data: ProfilesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`profiles/${profileId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Profiles: ${formatError(error)}`);
    return false;
  }
}

export type ProfilesRequestUpdate = Partial<ProfilesRequest>;

/**
 * Build a Profiles update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateProfiles(profileId: string, data: ProfilesRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `profiles/${profileId}`, document: doc };
}

/**
 * Owner only (existing address must equal @user.address). The address field cannot be changed to another wallet. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateProfiles(profileId: string, data: ProfilesRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`profiles/${profileId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Profiles: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Any authenticated user (wallet connected) can read profiles. Shows all fields.
   (Get Single Item)
 */
export async function getProfiles(profileId: string): Promise<ProfilesResponse | null> {
  try {
    const result = await get(`profiles/${profileId}`);
    return result as ProfilesResponse | null;
  } catch (error) {
    console.error(`Error getting Profiles: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Profiles document. (
  Read Operation Details: Any authenticated user (wallet connected) can read profiles. Shows all fields.
  )
 */
export function subscribeProfiles(callback: (data: ProfilesResponse | null) => void, profileId: string): Promise<() => Promise<void>> {
  return subscribe(`profiles/${profileId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as ProfilesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Profiles at path '${`profiles/${profileId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Profiles items from collection profiles
 
  Read Operation Details: Any authenticated user (wallet connected) can read profiles. Shows all fields.
  
 */
export async function getManyProfiles(filter: string = ""): Promise<ProfilesResponse[]> {
  try {
    const results = await get("profiles", { prompt: filter });
    return Array.isArray(results) ? results as ProfilesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Profiles collection at path 'profiles': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Profiles collection at profiles
 
  Read Operation Details: Any authenticated user (wallet connected) can read profiles. Shows all fields.
  
 */
export function subscribeManyProfiles(callback: (data: ProfilesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("profiles", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as ProfilesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Profiles collection at path '${"profiles"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Profiles items from collection profiles
 
  Read Operation Details: Any authenticated user (wallet connected) can read profiles. Shows all fields.
  
 */
export async function getAllProfiles(filter: string = ""): Promise<ProfilesResponse[]> {
  try {
    const results = await get("profiles", { prompt: filter });
    return Array.isArray(results) ? results as ProfilesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Profiles collection at path 'profiles': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Profiles collection at profiles
 
  Read Operation Details: Any authenticated user (wallet connected) can read profiles. Shows all fields.
  
 */
export function subscribeAllProfiles(callback: (data: ProfilesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("profiles", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as ProfilesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Profiles collection at path '${"profiles"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Owner only (address == @user.address).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteProfiles(profileId: string): Promise<boolean> {
  try {
    const succeeded = await set(`profiles/${profileId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Profiles: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Profiles for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteProfiles(profileId: string): DocumentOperation {
  return { path: `profiles/${profileId}`, document: null };
}

// --- Path: materials/$materialId ---

export interface MaterialsRequest {
  title: string;
  fileType: string;
  fileUrl?: string;
  textContent?: string;
  sizeBytes?: number | TimeOperation | IncrementOperation | TokenAmount;
  uploadedBy: AddressType;
  status: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface MaterialsResponse {
  title: string;
  fileType: string;
  fileUrl?: string;
  textContent?: string;
  sizeBytes?: number;
  uploadedBy: string;
  status: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Materials operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildMaterials(materialId: string, data: MaterialsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `materials/${materialId}`, document: doc };
}

/**
 * Authenticated users only. uploadedBy must equal @user.address. createdAt is Unix seconds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setMaterials(materialId: string, data: MaterialsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`materials/${materialId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Materials: ${formatError(error)}`);
    return false;
  }
}

export type MaterialsRequestUpdate = Partial<MaterialsRequest>;

/**
 * Build a Materials update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateMaterials(materialId: string, data: MaterialsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `materials/${materialId}`, document: doc };
}

/**
 * Owner only. uploadedBy cannot be reassigned to another wallet. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateMaterials(materialId: string, data: MaterialsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`materials/${materialId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Materials: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Owner only (uploadedBy == @user.address).
   (Get Single Item)
 */
export async function getMaterials(materialId: string): Promise<MaterialsResponse | null> {
  try {
    const result = await get(`materials/${materialId}`);
    return result as MaterialsResponse | null;
  } catch (error) {
    console.error(`Error getting Materials: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Materials document. (
  Read Operation Details: Owner only (uploadedBy == @user.address).
  )
 */
export function subscribeMaterials(callback: (data: MaterialsResponse | null) => void, materialId: string): Promise<() => Promise<void>> {
  return subscribe(`materials/${materialId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as MaterialsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Materials at path '${`materials/${materialId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Materials items from collection materials
 
  Read Operation Details: Owner only (uploadedBy == @user.address).
  
 */
export async function getManyMaterials(filter: string = ""): Promise<MaterialsResponse[]> {
  try {
    const results = await get("materials", { prompt: filter });
    return Array.isArray(results) ? results as MaterialsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Materials collection at path 'materials': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Materials collection at materials
 
  Read Operation Details: Owner only (uploadedBy == @user.address).
  
 */
export function subscribeManyMaterials(callback: (data: MaterialsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("materials", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as MaterialsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Materials collection at path '${"materials"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Materials items from collection materials
 
  Read Operation Details: Owner only (uploadedBy == @user.address).
  
 */
export async function getAllMaterials(filter: string = ""): Promise<MaterialsResponse[]> {
  try {
    const results = await get("materials", { prompt: filter });
    return Array.isArray(results) ? results as MaterialsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Materials collection at path 'materials': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Materials collection at materials
 
  Read Operation Details: Owner only (uploadedBy == @user.address).
  
 */
export function subscribeAllMaterials(callback: (data: MaterialsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("materials", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as MaterialsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Materials collection at path '${"materials"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Owner only (uploadedBy == @user.address).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteMaterials(materialId: string): Promise<boolean> {
  try {
    const succeeded = await set(`materials/${materialId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Materials: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Materials for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteMaterials(materialId: string): DocumentOperation {
  return { path: `materials/${materialId}`, document: null };
}

// --- Path: songs/$songId ---

export interface SongsRequest {
  title: string;
  materialId?: string;
  genre: string;
  vocalStyle: string;
  durationSec: number | TimeOperation | IncrementOperation | TokenAmount;
  audioUrl?: string;
  lyrics?: string;
  coverUrl?: string;
  status: string;
  createdBy: AddressType;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
  lyricsTimestamps?: string;
  generationError?: string;
}

export interface SongsResponse {
  title: string;
  materialId?: string;
  genre: string;
  vocalStyle: string;
  durationSec: number;
  audioUrl?: string;
  lyrics?: string;
  coverUrl?: string;
  status: string;
  createdBy: string;
  createdAt: number;
  lyricsTimestamps?: string;
  generationError?: string;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Songs operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSongs(songId: string, data: SongsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `songs/${songId}`, document: doc };
}

/**
 * Authenticated users only. createdBy must equal @user.address. durationSec is required (pass 0 for placeholders). audioUrl/lyrics/coverUrl are optional placeholders. createdAt is Unix seconds. Optional: lyricsTimestamps (JSON array of {line,tSec} for synced lyrics), generationError (human-readable error message for retry UX). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSongs(songId: string, data: SongsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`songs/${songId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Songs: ${formatError(error)}`);
    return false;
  }
}

export type SongsRequestUpdate = Partial<SongsRequest>;

/**
 * Build a Songs update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateSongs(songId: string, data: SongsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `songs/${songId}`, document: doc };
}

/**
 * Owner only. createdBy cannot be reassigned to another wallet. lyricsTimestamps and generationError are optional and updatable by the owner. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateSongs(songId: string, data: SongsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`songs/${songId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Songs: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Owner only (createdBy == @user.address).
   (Get Single Item)
 */
export async function getSongs(songId: string): Promise<SongsResponse | null> {
  try {
    const result = await get(`songs/${songId}`);
    return result as SongsResponse | null;
  } catch (error) {
    console.error(`Error getting Songs: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Songs document. (
  Read Operation Details: Owner only (createdBy == @user.address).
  )
 */
export function subscribeSongs(callback: (data: SongsResponse | null) => void, songId: string): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SongsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Songs at path '${`songs/${songId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Songs items from collection songs
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export async function getManySongs(filter: string = ""): Promise<SongsResponse[]> {
  try {
    const results = await get("songs", { prompt: filter });
    return Array.isArray(results) ? results as SongsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Songs collection at path 'songs': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Songs collection at songs
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export function subscribeManySongs(callback: (data: SongsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("songs", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Songs collection at path '${"songs"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Songs items from collection songs
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export async function getAllSongs(filter: string = ""): Promise<SongsResponse[]> {
  try {
    const results = await get("songs", { prompt: filter });
    return Array.isArray(results) ? results as SongsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Songs collection at path 'songs': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Songs collection at songs
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export function subscribeAllSongs(callback: (data: SongsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("songs", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Songs collection at path '${"songs"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Owner only (createdBy == @user.address).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteSongs(songId: string): Promise<boolean> {
  try {
    const succeeded = await set(`songs/${songId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Songs: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Songs for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteSongs(songId: string): DocumentOperation {
  return { path: `songs/${songId}`, document: null };
}

// --- Path: playlists/$playlistId ---

export interface PlaylistsRequest {
  name: string;
  description?: string;
  coverUrl?: string;
  createdBy: AddressType;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PlaylistsResponse {
  name: string;
  description?: string;
  coverUrl?: string;
  createdBy: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Playlists operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPlaylists(playlistId: string, data: PlaylistsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `playlists/${playlistId}`, document: doc };
}

/**
 * Authenticated users only. createdBy must equal @user.address. Add songs via the playlistSongs subcollection. createdAt is Unix seconds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPlaylists(playlistId: string, data: PlaylistsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`playlists/${playlistId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Playlists: ${formatError(error)}`);
    return false;
  }
}

export type PlaylistsRequestUpdate = Partial<PlaylistsRequest>;

/**
 * Build a Playlists update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdatePlaylists(playlistId: string, data: PlaylistsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `playlists/${playlistId}`, document: doc };
}

/**
 * Owner only. createdBy cannot be reassigned to another wallet. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updatePlaylists(playlistId: string, data: PlaylistsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`playlists/${playlistId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Playlists: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Owner only (createdBy == @user.address).
   (Get Single Item)
 */
export async function getPlaylists(playlistId: string): Promise<PlaylistsResponse | null> {
  try {
    const result = await get(`playlists/${playlistId}`);
    return result as PlaylistsResponse | null;
  } catch (error) {
    console.error(`Error getting Playlists: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Playlists document. (
  Read Operation Details: Owner only (createdBy == @user.address).
  )
 */
export function subscribePlaylists(callback: (data: PlaylistsResponse | null) => void, playlistId: string): Promise<() => Promise<void>> {
  return subscribe(`playlists/${playlistId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PlaylistsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Playlists at path '${`playlists/${playlistId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Playlists items from collection playlists
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export async function getManyPlaylists(filter: string = ""): Promise<PlaylistsResponse[]> {
  try {
    const results = await get("playlists", { prompt: filter });
    return Array.isArray(results) ? results as PlaylistsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Playlists collection at path 'playlists': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Playlists collection at playlists
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export function subscribeManyPlaylists(callback: (data: PlaylistsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("playlists", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PlaylistsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Playlists collection at path '${"playlists"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Playlists items from collection playlists
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export async function getAllPlaylists(filter: string = ""): Promise<PlaylistsResponse[]> {
  try {
    const results = await get("playlists", { prompt: filter });
    return Array.isArray(results) ? results as PlaylistsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Playlists collection at path 'playlists': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Playlists collection at playlists
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export function subscribeAllPlaylists(callback: (data: PlaylistsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("playlists", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PlaylistsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Playlists collection at path '${"playlists"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Owner only (createdBy == @user.address).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deletePlaylists(playlistId: string): Promise<boolean> {
  try {
    const succeeded = await set(`playlists/${playlistId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Playlists: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Playlists for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeletePlaylists(playlistId: string): DocumentOperation {
  return { path: `playlists/${playlistId}`, document: null };
}

// --- Path: playlists/$playlistId/playlistSongs/$entryId ---

export interface PlaylistsPlaylistSongsRequest {
  songId: string;
  position: number | TimeOperation | IncrementOperation | TokenAmount;
  addedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PlaylistsPlaylistSongsResponse {
  songId: string;
  position: number;
  addedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a PlaylistsPlaylistSongs operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPlaylistsPlaylistSongs(playlistId: string, entryId: string, data: PlaylistsPlaylistSongsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `playlists/${playlistId}/playlistSongs/${entryId}`, document: doc };
}

/**
 * Owner of the parent playlist only (playlist.createdBy == @user.address). songId references a song; position orders the entry; addedAt is Unix seconds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPlaylistsPlaylistSongs(playlistId: string, entryId: string, data: PlaylistsPlaylistSongsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`playlists/${playlistId}/playlistSongs/${entryId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PlaylistsPlaylistSongs: ${formatError(error)}`);
    return false;
  }
}

export type PlaylistsPlaylistSongsRequestUpdate = Partial<PlaylistsPlaylistSongsRequest>;

/**
 * Build a PlaylistsPlaylistSongs update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdatePlaylistsPlaylistSongs(playlistId: string, entryId: string, data: PlaylistsPlaylistSongsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `playlists/${playlistId}/playlistSongs/${entryId}`, document: doc };
}

/**
 * Owner of the parent playlist only (e.g. to reorder position). (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updatePlaylistsPlaylistSongs(playlistId: string, entryId: string, data: PlaylistsPlaylistSongsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`playlists/${playlistId}/playlistSongs/${entryId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating PlaylistsPlaylistSongs: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Owner of the parent playlist only.
   (Get Single Item)
 */
export async function getPlaylistsPlaylistSongs(playlistId: string, entryId: string): Promise<PlaylistsPlaylistSongsResponse | null> {
  try {
    const result = await get(`playlists/${playlistId}/playlistSongs/${entryId}`);
    return result as PlaylistsPlaylistSongsResponse | null;
  } catch (error) {
    console.error(`Error getting PlaylistsPlaylistSongs: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PlaylistsPlaylistSongs document. (
  Read Operation Details: Owner of the parent playlist only.
  )
 */
export function subscribePlaylistsPlaylistSongs(callback: (data: PlaylistsPlaylistSongsResponse | null) => void, playlistId: string, entryId: string): Promise<() => Promise<void>> {
  return subscribe(`playlists/${playlistId}/playlistSongs/${entryId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PlaylistsPlaylistSongsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PlaylistsPlaylistSongs at path '${`playlists/${playlistId}/playlistSongs/${entryId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PlaylistsPlaylistSongs items from collection playlists/${playlistId}/playlistSongs
 
  Read Operation Details: Owner of the parent playlist only.
  
 */
export async function getManyPlaylistsPlaylistSongs(playlistId: string, filter: string = ""): Promise<PlaylistsPlaylistSongsResponse[]> {
  try {
    const results = await get(`playlists/${playlistId}/playlistSongs`, { prompt: filter });
    return Array.isArray(results) ? results as PlaylistsPlaylistSongsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PlaylistsPlaylistSongs collection at path 'playlists/${playlistId}/playlistSongs': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PlaylistsPlaylistSongs collection at playlists/${playlistId}/playlistSongs
 
  Read Operation Details: Owner of the parent playlist only.
  
 */
export function subscribeManyPlaylistsPlaylistSongs(callback: (data: PlaylistsPlaylistSongsResponse[]) => void, playlistId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`playlists/${playlistId}/playlistSongs`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PlaylistsPlaylistSongsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PlaylistsPlaylistSongs collection at path '${`playlists/${playlistId}/playlistSongs`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PlaylistsPlaylistSongs items from collection playlists/${playlistId}/playlistSongs
 
  Read Operation Details: Owner of the parent playlist only.
  
 */
export async function getAllPlaylistsPlaylistSongs(playlistId: string, filter: string = ""): Promise<PlaylistsPlaylistSongsResponse[]> {
  try {
    const results = await get(`playlists/*/playlistSongs`, { prompt: filter });
    return Array.isArray(results) ? results as PlaylistsPlaylistSongsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PlaylistsPlaylistSongs collection at path 'playlists/${playlistId}/playlistSongs': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PlaylistsPlaylistSongs collection at playlists/${playlistId}/playlistSongs
 
  Read Operation Details: Owner of the parent playlist only.
  
 */
export function subscribeAllPlaylistsPlaylistSongs(callback: (data: PlaylistsPlaylistSongsResponse[]) => void, playlistId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`playlists/*/playlistSongs`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PlaylistsPlaylistSongsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PlaylistsPlaylistSongs collection at path '${`playlists/*/playlistSongs`}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Owner of the parent playlist only (removes the song from the playlist).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deletePlaylistsPlaylistSongs(playlistId: string, entryId: string): Promise<boolean> {
  try {
    const succeeded = await set(`playlists/${playlistId}/playlistSongs/${entryId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting PlaylistsPlaylistSongs: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for PlaylistsPlaylistSongs for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeletePlaylistsPlaylistSongs(playlistId: string, entryId: string): DocumentOperation {
  return { path: `playlists/${playlistId}/playlistSongs/${entryId}`, document: null };
}

// --- Path: favorites/$favoriteId ---

export interface FavoritesRequest {
  userId: AddressType;
  songId: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface FavoritesResponse {
  userId: string;
  songId: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Favorites operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildFavorites(favoriteId: string, data: FavoritesRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `favorites/${favoriteId}`, document: doc };
}

/**
 * Authenticated users only. userId must equal @user.address. songId references a song document. createdAt is Unix seconds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setFavorites(favoriteId: string, data: FavoritesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`favorites/${favoriteId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Favorites: ${formatError(error)}`);
    return false;
  }
}

export type FavoritesRequestUpdate = Partial<FavoritesRequest>;

/**
 * Build a Favorites update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateFavorites(favoriteId: string, data: FavoritesRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `favorites/${favoriteId}`, document: doc };
}

/**
 * Owner only. userId cannot be reassigned to another wallet. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateFavorites(favoriteId: string, data: FavoritesRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`favorites/${favoriteId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Favorites: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Owner only (userId == @user.address).
   (Get Single Item)
 */
export async function getFavorites(favoriteId: string): Promise<FavoritesResponse | null> {
  try {
    const result = await get(`favorites/${favoriteId}`);
    return result as FavoritesResponse | null;
  } catch (error) {
    console.error(`Error getting Favorites: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Favorites document. (
  Read Operation Details: Owner only (userId == @user.address).
  )
 */
export function subscribeFavorites(callback: (data: FavoritesResponse | null) => void, favoriteId: string): Promise<() => Promise<void>> {
  return subscribe(`favorites/${favoriteId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as FavoritesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Favorites at path '${`favorites/${favoriteId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Favorites items from collection favorites
 
  Read Operation Details: Owner only (userId == @user.address).
  
 */
export async function getManyFavorites(filter: string = ""): Promise<FavoritesResponse[]> {
  try {
    const results = await get("favorites", { prompt: filter });
    return Array.isArray(results) ? results as FavoritesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Favorites collection at path 'favorites': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Favorites collection at favorites
 
  Read Operation Details: Owner only (userId == @user.address).
  
 */
export function subscribeManyFavorites(callback: (data: FavoritesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("favorites", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FavoritesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Favorites collection at path '${"favorites"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Favorites items from collection favorites
 
  Read Operation Details: Owner only (userId == @user.address).
  
 */
export async function getAllFavorites(filter: string = ""): Promise<FavoritesResponse[]> {
  try {
    const results = await get("favorites", { prompt: filter });
    return Array.isArray(results) ? results as FavoritesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Favorites collection at path 'favorites': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Favorites collection at favorites
 
  Read Operation Details: Owner only (userId == @user.address).
  
 */
export function subscribeAllFavorites(callback: (data: FavoritesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("favorites", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FavoritesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Favorites collection at path '${"favorites"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Owner only (userId == @user.address).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteFavorites(favoriteId: string): Promise<boolean> {
  try {
    const succeeded = await set(`favorites/${favoriteId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Favorites: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Favorites for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteFavorites(favoriteId: string): DocumentOperation {
  return { path: `favorites/${favoriteId}`, document: null };
}

// --- Path: studySessions/$sessionId ---

export interface StudySessionsRequest {
  name: string;
  durationSec?: number | TimeOperation | IncrementOperation | TokenAmount;
  createdBy: AddressType;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
  materialId?: string;
  status?: string;
  shortSummary?: string;
  detailedSummary?: string;
  keyConcepts?: string;
  flashcards?: string;
  quiz?: string;
}

export interface StudySessionsResponse {
  name: string;
  durationSec?: number;
  createdBy: string;
  createdAt: number;
  materialId?: string;
  status?: string;
  shortSummary?: string;
  detailedSummary?: string;
  keyConcepts?: string;
  flashcards?: string;
  quiz?: string;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a StudySessions operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildStudySessions(sessionId: string, data: StudySessionsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `studySessions/${sessionId}`, document: doc };
}

/**
 * Authenticated users only. createdBy must equal @user.address. Add songs via the sessionSongs subcollection. createdAt is Unix seconds. Optional Learning Package fields: materialId (source material), status ('generating'|'ready'|'failed'), shortSummary, detailedSummary, keyConcepts (JSON array), flashcards (JSON array of {question,answer}), quiz (JSON array of {question,options,answerIndex,explanation}). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setStudySessions(sessionId: string, data: StudySessionsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`studySessions/${sessionId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting StudySessions: ${formatError(error)}`);
    return false;
  }
}

export type StudySessionsRequestUpdate = Partial<StudySessionsRequest>;

/**
 * Build a StudySessions update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateStudySessions(sessionId: string, data: StudySessionsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `studySessions/${sessionId}`, document: doc };
}

/**
 * Owner only. createdBy cannot be reassigned to another wallet. Optional Learning Package fields can be updated by the owner. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateStudySessions(sessionId: string, data: StudySessionsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`studySessions/${sessionId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating StudySessions: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Owner only (createdBy == @user.address).
   (Get Single Item)
 */
export async function getStudySessions(sessionId: string): Promise<StudySessionsResponse | null> {
  try {
    const result = await get(`studySessions/${sessionId}`);
    return result as StudySessionsResponse | null;
  } catch (error) {
    console.error(`Error getting StudySessions: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single StudySessions document. (
  Read Operation Details: Owner only (createdBy == @user.address).
  )
 */
export function subscribeStudySessions(callback: (data: StudySessionsResponse | null) => void, sessionId: string): Promise<() => Promise<void>> {
  return subscribe(`studySessions/${sessionId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as StudySessionsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to StudySessions at path '${`studySessions/${sessionId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many StudySessions items from collection studySessions
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export async function getManyStudySessions(filter: string = ""): Promise<StudySessionsResponse[]> {
  try {
    const results = await get("studySessions", { prompt: filter });
    return Array.isArray(results) ? results as StudySessionsResponse[] : [];
  } catch (error) {
    console.error(`Error getting StudySessions collection at path 'studySessions': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in StudySessions collection at studySessions
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export function subscribeManyStudySessions(callback: (data: StudySessionsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("studySessions", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as StudySessionsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to StudySessions collection at path '${"studySessions"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all StudySessions items from collection studySessions
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export async function getAllStudySessions(filter: string = ""): Promise<StudySessionsResponse[]> {
  try {
    const results = await get("studySessions", { prompt: filter });
    return Array.isArray(results) ? results as StudySessionsResponse[] : [];
  } catch (error) {
    console.error(`Error getting StudySessions collection at path 'studySessions': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in StudySessions collection at studySessions
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export function subscribeAllStudySessions(callback: (data: StudySessionsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("studySessions", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as StudySessionsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to StudySessions collection at path '${"studySessions"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Owner only (createdBy == @user.address).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteStudySessions(sessionId: string): Promise<boolean> {
  try {
    const succeeded = await set(`studySessions/${sessionId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting StudySessions: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for StudySessions for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteStudySessions(sessionId: string): DocumentOperation {
  return { path: `studySessions/${sessionId}`, document: null };
}

// --- Path: studySessions/$sessionId/sessionSongs/$entryId ---

export interface StudySessionsSessionSongsRequest {
  songId: string;
  position: number | TimeOperation | IncrementOperation | TokenAmount;
  addedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface StudySessionsSessionSongsResponse {
  songId: string;
  position: number;
  addedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a StudySessionsSessionSongs operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildStudySessionsSessionSongs(sessionId: string, entryId: string, data: StudySessionsSessionSongsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `studySessions/${sessionId}/sessionSongs/${entryId}`, document: doc };
}

/**
 * Owner of the parent session only (session.createdBy == @user.address). songId references a song; position orders the entry; addedAt is Unix seconds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setStudySessionsSessionSongs(sessionId: string, entryId: string, data: StudySessionsSessionSongsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`studySessions/${sessionId}/sessionSongs/${entryId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting StudySessionsSessionSongs: ${formatError(error)}`);
    return false;
  }
}

export type StudySessionsSessionSongsRequestUpdate = Partial<StudySessionsSessionSongsRequest>;

/**
 * Build a StudySessionsSessionSongs update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateStudySessionsSessionSongs(sessionId: string, entryId: string, data: StudySessionsSessionSongsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `studySessions/${sessionId}/sessionSongs/${entryId}`, document: doc };
}

/**
 * Owner of the parent session only (e.g. to reorder position). (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateStudySessionsSessionSongs(sessionId: string, entryId: string, data: StudySessionsSessionSongsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`studySessions/${sessionId}/sessionSongs/${entryId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating StudySessionsSessionSongs: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Owner of the parent session only.
   (Get Single Item)
 */
export async function getStudySessionsSessionSongs(sessionId: string, entryId: string): Promise<StudySessionsSessionSongsResponse | null> {
  try {
    const result = await get(`studySessions/${sessionId}/sessionSongs/${entryId}`);
    return result as StudySessionsSessionSongsResponse | null;
  } catch (error) {
    console.error(`Error getting StudySessionsSessionSongs: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single StudySessionsSessionSongs document. (
  Read Operation Details: Owner of the parent session only.
  )
 */
export function subscribeStudySessionsSessionSongs(callback: (data: StudySessionsSessionSongsResponse | null) => void, sessionId: string, entryId: string): Promise<() => Promise<void>> {
  return subscribe(`studySessions/${sessionId}/sessionSongs/${entryId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as StudySessionsSessionSongsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to StudySessionsSessionSongs at path '${`studySessions/${sessionId}/sessionSongs/${entryId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many StudySessionsSessionSongs items from collection studySessions/${sessionId}/sessionSongs
 
  Read Operation Details: Owner of the parent session only.
  
 */
export async function getManyStudySessionsSessionSongs(sessionId: string, filter: string = ""): Promise<StudySessionsSessionSongsResponse[]> {
  try {
    const results = await get(`studySessions/${sessionId}/sessionSongs`, { prompt: filter });
    return Array.isArray(results) ? results as StudySessionsSessionSongsResponse[] : [];
  } catch (error) {
    console.error(`Error getting StudySessionsSessionSongs collection at path 'studySessions/${sessionId}/sessionSongs': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in StudySessionsSessionSongs collection at studySessions/${sessionId}/sessionSongs
 
  Read Operation Details: Owner of the parent session only.
  
 */
export function subscribeManyStudySessionsSessionSongs(callback: (data: StudySessionsSessionSongsResponse[]) => void, sessionId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`studySessions/${sessionId}/sessionSongs`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as StudySessionsSessionSongsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to StudySessionsSessionSongs collection at path '${`studySessions/${sessionId}/sessionSongs`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all StudySessionsSessionSongs items from collection studySessions/${sessionId}/sessionSongs
 
  Read Operation Details: Owner of the parent session only.
  
 */
export async function getAllStudySessionsSessionSongs(sessionId: string, filter: string = ""): Promise<StudySessionsSessionSongsResponse[]> {
  try {
    const results = await get(`studySessions/*/sessionSongs`, { prompt: filter });
    return Array.isArray(results) ? results as StudySessionsSessionSongsResponse[] : [];
  } catch (error) {
    console.error(`Error getting StudySessionsSessionSongs collection at path 'studySessions/${sessionId}/sessionSongs': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in StudySessionsSessionSongs collection at studySessions/${sessionId}/sessionSongs
 
  Read Operation Details: Owner of the parent session only.
  
 */
export function subscribeAllStudySessionsSessionSongs(callback: (data: StudySessionsSessionSongsResponse[]) => void, sessionId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`studySessions/*/sessionSongs`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as StudySessionsSessionSongsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to StudySessionsSessionSongs collection at path '${`studySessions/*/sessionSongs`}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Owner of the parent session only (removes the song from the session).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteStudySessionsSessionSongs(sessionId: string, entryId: string): Promise<boolean> {
  try {
    const succeeded = await set(`studySessions/${sessionId}/sessionSongs/${entryId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting StudySessionsSessionSongs: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for StudySessionsSessionSongs for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteStudySessionsSessionSongs(sessionId: string, entryId: string): DocumentOperation {
  return { path: `studySessions/${sessionId}/sessionSongs/${entryId}`, document: null };
}

// --- Path: history/$historyId ---

export interface HistoryRequest {
  userId: AddressType;
  songId: string;
  playedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface HistoryResponse {
  userId: string;
  songId: string;
  playedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a History operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildHistory(historyId: string, data: HistoryRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `history/${historyId}`, document: doc };
}

/**
 * Authenticated users only. userId must equal @user.address. playedAt is Unix seconds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setHistory(historyId: string, data: HistoryRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`history/${historyId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting History: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Owner only (userId == @user.address).
   (Get Single Item)
 */
export async function getHistory(historyId: string): Promise<HistoryResponse | null> {
  try {
    const result = await get(`history/${historyId}`);
    return result as HistoryResponse | null;
  } catch (error) {
    console.error(`Error getting History: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single History document. (
  Read Operation Details: Owner only (userId == @user.address).
  )
 */
export function subscribeHistory(callback: (data: HistoryResponse | null) => void, historyId: string): Promise<() => Promise<void>> {
  return subscribe(`history/${historyId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as HistoryResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to History at path '${`history/${historyId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many History items from collection history
 
  Read Operation Details: Owner only (userId == @user.address).
  
 */
export async function getManyHistory(filter: string = ""): Promise<HistoryResponse[]> {
  try {
    const results = await get("history", { prompt: filter });
    return Array.isArray(results) ? results as HistoryResponse[] : [];
  } catch (error) {
    console.error(`Error getting History collection at path 'history': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in History collection at history
 
  Read Operation Details: Owner only (userId == @user.address).
  
 */
export function subscribeManyHistory(callback: (data: HistoryResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("history", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as HistoryResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to History collection at path '${"history"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all History items from collection history
 
  Read Operation Details: Owner only (userId == @user.address).
  
 */
export async function getAllHistory(filter: string = ""): Promise<HistoryResponse[]> {
  try {
    const results = await get("history", { prompt: filter });
    return Array.isArray(results) ? results as HistoryResponse[] : [];
  } catch (error) {
    console.error(`Error getting History collection at path 'history': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in History collection at history
 
  Read Operation Details: Owner only (userId == @user.address).
  
 */
export function subscribeAllHistory(callback: (data: HistoryResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("history", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as HistoryResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to History collection at path '${"history"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Owner only (userId == @user.address) can remove their own history entries.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteHistory(historyId: string): Promise<boolean> {
  try {
    const succeeded = await set(`history/${historyId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting History: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for History for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteHistory(historyId: string): DocumentOperation {
  return { path: `history/${historyId}`, document: null };
}

// --- End Generated SDK ---
