// Generated by TaroBase SDK Generator: 2026-07-15T16:35:00.350Z
// Collection: history/$historyId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * Playback history entry. Owner-scoped by userId; immutable once created.
 */

export interface HistoryRequest {
  userId: AddressType;
  songId: string;
  playedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface HistoryResponse {
  userId: string;
  songId: string;
  playedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a History operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildHistory(historyId: string, data: HistoryRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `history/${historyId}`, document: doc };
}

/**
 * Authenticated users only. userId must equal @user.address. playedAt is Unix seconds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setHistory(historyId: string, data: HistoryRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`history/${historyId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting History: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Owner only (userId == @user.address).
   (Get Single Item)
 */
export async function getHistory(historyId: string): Promise<HistoryResponse | null> {
  try {
    const result = await get(`history/${historyId}`);
    return result as HistoryResponse | null;
  } catch (error) {
    console.error(`Error getting History: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single History document. (
  Read Operation Details: Owner only (userId == @user.address).
  )
 */
export function subscribeHistory(callback: (data: HistoryResponse | null) => void, historyId: string): Promise<() => Promise<void>> {
  return subscribe(`history/${historyId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as HistoryResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to History at path '${`history/${historyId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many History items from collection history
 
  Read Operation Details: Owner only (userId == @user.address).
  
 */
export async function getManyHistory(filter: string = ""): Promise<HistoryResponse[]> {
  try {
    const results = await get("history", { prompt: filter });
    return Array.isArray(results) ? results as HistoryResponse[] : [];
  } catch (error) {
    console.error(`Error getting History collection at path 'history': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in History collection at history
 
  Read Operation Details: Owner only (userId == @user.address).
  
 */
export function subscribeManyHistory(callback: (data: HistoryResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("history", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as HistoryResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to History collection at path '${"history"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all History items from collection history
 
  Read Operation Details: Owner only (userId == @user.address).
  
 */
export async function getAllHistory(filter: string = ""): Promise<HistoryResponse[]> {
  try {
    const results = await get("history", { prompt: filter });
    return Array.isArray(results) ? results as HistoryResponse[] : [];
  } catch (error) {
    console.error(`Error getting History collection at path 'history': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in History collection at history
 
  Read Operation Details: Owner only (userId == @user.address).
  
 */
export function subscribeAllHistory(callback: (data: HistoryResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("history", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as HistoryResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to History collection at path '${"history"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Owner only (userId == @user.address) can remove their own history entries.
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteHistory(historyId: string): Promise<boolean> {
  try {
    const succeeded = await set(`history/${historyId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting History: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for History for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteHistory(historyId: string): DocumentOperation {
  return { path: `history/${historyId}`, document: null };
}

