// Generated by TaroBase SDK Generator: 2026-07-15T16:35:00.350Z
// Collection: materials/$materialId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * An uploaded study document (pdf/docx/txt/text). Owner-scoped: only uploadedBy == @user.address can read/create/update/delete.
 */

export interface MaterialsRequest {
  title: string;
  fileType: string;
  fileUrl?: string;
  textContent?: string;
  sizeBytes?: number | TimeOperation | IncrementOperation | TokenAmount;
  uploadedBy: AddressType;
  status: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface MaterialsResponse {
  title: string;
  fileType: string;
  fileUrl?: string;
  textContent?: string;
  sizeBytes?: number;
  uploadedBy: string;
  status: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Materials operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildMaterials(materialId: string, data: MaterialsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `materials/${materialId}`, document: doc };
}

/**
 * Authenticated users only. uploadedBy must equal @user.address. createdAt is Unix seconds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setMaterials(materialId: string, data: MaterialsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`materials/${materialId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Materials: ${formatError(error)}`);
    return false;
  }
}

export type MaterialsRequestUpdate = Partial<MaterialsRequest>;

/**
 * Build a Materials update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateMaterials(materialId: string, data: MaterialsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `materials/${materialId}`, document: doc };
}

/**
 * Owner only. uploadedBy cannot be reassigned to another wallet. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateMaterials(materialId: string, data: MaterialsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`materials/${materialId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Materials: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Owner only (uploadedBy == @user.address).
   (Get Single Item)
 */
export async function getMaterials(materialId: string): Promise<MaterialsResponse | null> {
  try {
    const result = await get(`materials/${materialId}`);
    return result as MaterialsResponse | null;
  } catch (error) {
    console.error(`Error getting Materials: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Materials document. (
  Read Operation Details: Owner only (uploadedBy == @user.address).
  )
 */
export function subscribeMaterials(callback: (data: MaterialsResponse | null) => void, materialId: string): Promise<() => Promise<void>> {
  return subscribe(`materials/${materialId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as MaterialsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Materials at path '${`materials/${materialId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Materials items from collection materials
 
  Read Operation Details: Owner only (uploadedBy == @user.address).
  
 */
export async function getManyMaterials(filter: string = ""): Promise<MaterialsResponse[]> {
  try {
    const results = await get("materials", { prompt: filter });
    return Array.isArray(results) ? results as MaterialsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Materials collection at path 'materials': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Materials collection at materials
 
  Read Operation Details: Owner only (uploadedBy == @user.address).
  
 */
export function subscribeManyMaterials(callback: (data: MaterialsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("materials", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as MaterialsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Materials collection at path '${"materials"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Materials items from collection materials
 
  Read Operation Details: Owner only (uploadedBy == @user.address).
  
 */
export async function getAllMaterials(filter: string = ""): Promise<MaterialsResponse[]> {
  try {
    const results = await get("materials", { prompt: filter });
    return Array.isArray(results) ? results as MaterialsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Materials collection at path 'materials': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Materials collection at materials
 
  Read Operation Details: Owner only (uploadedBy == @user.address).
  
 */
export function subscribeAllMaterials(callback: (data: MaterialsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("materials", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as MaterialsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Materials collection at path '${"materials"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Owner only (uploadedBy == @user.address).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteMaterials(materialId: string): Promise<boolean> {
  try {
    const succeeded = await set(`materials/${materialId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Materials: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Materials for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteMaterials(materialId: string): DocumentOperation {
  return { path: `materials/${materialId}`, document: null };
}

