// Generated by TaroBase SDK Generator: 2026-07-15T16:35:00.350Z
// Collection: profiles/$profileId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * User profile for StudyBeats AI. One per wallet. Readable by any authenticated user; only the owner (address == @user.address) can create/update/delete.
 */

export interface ProfilesRequest {
  address: AddressType;
  displayName: string;
  avatarUrl?: string;
  bio?: string;
  plan: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface ProfilesResponse {
  address: string;
  displayName: string;
  avatarUrl?: string;
  bio?: string;
  plan: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Profiles operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildProfiles(profileId: string, data: ProfilesRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `profiles/${profileId}`, document: doc };
}

/**
 * Authenticated users only. The address field must equal @user.address (users create only their own profile). createdAt is Unix seconds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setProfiles(profileId: string, data: ProfilesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`profiles/${profileId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Profiles: ${formatError(error)}`);
    return false;
  }
}

export type ProfilesRequestUpdate = Partial<ProfilesRequest>;

/**
 * Build a Profiles update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateProfiles(profileId: string, data: ProfilesRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `profiles/${profileId}`, document: doc };
}

/**
 * Owner only (existing address must equal @user.address). The address field cannot be changed to another wallet. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateProfiles(profileId: string, data: ProfilesRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`profiles/${profileId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Profiles: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Any authenticated user (wallet connected) can read profiles. Shows all fields.
   (Get Single Item)
 */
export async function getProfiles(profileId: string): Promise<ProfilesResponse | null> {
  try {
    const result = await get(`profiles/${profileId}`);
    return result as ProfilesResponse | null;
  } catch (error) {
    console.error(`Error getting Profiles: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Profiles document. (
  Read Operation Details: Any authenticated user (wallet connected) can read profiles. Shows all fields.
  )
 */
export function subscribeProfiles(callback: (data: ProfilesResponse | null) => void, profileId: string): Promise<() => Promise<void>> {
  return subscribe(`profiles/${profileId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as ProfilesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Profiles at path '${`profiles/${profileId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Profiles items from collection profiles
 
  Read Operation Details: Any authenticated user (wallet connected) can read profiles. Shows all fields.
  
 */
export async function getManyProfiles(filter: string = ""): Promise<ProfilesResponse[]> {
  try {
    const results = await get("profiles", { prompt: filter });
    return Array.isArray(results) ? results as ProfilesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Profiles collection at path 'profiles': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Profiles collection at profiles
 
  Read Operation Details: Any authenticated user (wallet connected) can read profiles. Shows all fields.
  
 */
export function subscribeManyProfiles(callback: (data: ProfilesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("profiles", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as ProfilesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Profiles collection at path '${"profiles"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Profiles items from collection profiles
 
  Read Operation Details: Any authenticated user (wallet connected) can read profiles. Shows all fields.
  
 */
export async function getAllProfiles(filter: string = ""): Promise<ProfilesResponse[]> {
  try {
    const results = await get("profiles", { prompt: filter });
    return Array.isArray(results) ? results as ProfilesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Profiles collection at path 'profiles': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Profiles collection at profiles
 
  Read Operation Details: Any authenticated user (wallet connected) can read profiles. Shows all fields.
  
 */
export function subscribeAllProfiles(callback: (data: ProfilesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("profiles", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as ProfilesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Profiles collection at path '${"profiles"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Owner only (address == @user.address).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteProfiles(profileId: string): Promise<boolean> {
  try {
    const succeeded = await set(`profiles/${profileId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Profiles: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Profiles for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteProfiles(profileId: string): DocumentOperation {
  return { path: `profiles/${profileId}`, document: null };
}

