// Generated by TaroBase SDK Generator: 2026-07-15T16:35:00.350Z
// Collection: studySessions/$sessionId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * A focus/study session grouping songs. Owner-scoped by createdBy. Song membership is stored in the sessionSongs subcollection.
 */

export interface StudySessionsRequest {
  name: string;
  durationSec?: number | TimeOperation | IncrementOperation | TokenAmount;
  createdBy: AddressType;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
  materialId?: string;
  status?: string;
  shortSummary?: string;
  detailedSummary?: string;
  keyConcepts?: string;
  flashcards?: string;
  quiz?: string;
}

export interface StudySessionsResponse {
  name: string;
  durationSec?: number;
  createdBy: string;
  createdAt: number;
  materialId?: string;
  status?: string;
  shortSummary?: string;
  detailedSummary?: string;
  keyConcepts?: string;
  flashcards?: string;
  quiz?: string;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a StudySessions operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildStudySessions(sessionId: string, data: StudySessionsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `studySessions/${sessionId}`, document: doc };
}

/**
 * Authenticated users only. createdBy must equal @user.address. Add songs via the sessionSongs subcollection. createdAt is Unix seconds. Optional Learning Package fields: materialId (source material), status ('generating'|'ready'|'failed'), shortSummary, detailedSummary, keyConcepts (JSON array), flashcards (JSON array of {question,answer}), quiz (JSON array of {question,options,answerIndex,explanation}). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setStudySessions(sessionId: string, data: StudySessionsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`studySessions/${sessionId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting StudySessions: ${formatError(error)}`);
    return false;
  }
}

export type StudySessionsRequestUpdate = Partial<StudySessionsRequest>;

/**
 * Build a StudySessions update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateStudySessions(sessionId: string, data: StudySessionsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `studySessions/${sessionId}`, document: doc };
}

/**
 * Owner only. createdBy cannot be reassigned to another wallet. Optional Learning Package fields can be updated by the owner. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateStudySessions(sessionId: string, data: StudySessionsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`studySessions/${sessionId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating StudySessions: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Owner only (createdBy == @user.address).
   (Get Single Item)
 */
export async function getStudySessions(sessionId: string): Promise<StudySessionsResponse | null> {
  try {
    const result = await get(`studySessions/${sessionId}`);
    return result as StudySessionsResponse | null;
  } catch (error) {
    console.error(`Error getting StudySessions: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single StudySessions document. (
  Read Operation Details: Owner only (createdBy == @user.address).
  )
 */
export function subscribeStudySessions(callback: (data: StudySessionsResponse | null) => void, sessionId: string): Promise<() => Promise<void>> {
  return subscribe(`studySessions/${sessionId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as StudySessionsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to StudySessions at path '${`studySessions/${sessionId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many StudySessions items from collection studySessions
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export async function getManyStudySessions(filter: string = ""): Promise<StudySessionsResponse[]> {
  try {
    const results = await get("studySessions", { prompt: filter });
    return Array.isArray(results) ? results as StudySessionsResponse[] : [];
  } catch (error) {
    console.error(`Error getting StudySessions collection at path 'studySessions': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in StudySessions collection at studySessions
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export function subscribeManyStudySessions(callback: (data: StudySessionsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("studySessions", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as StudySessionsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to StudySessions collection at path '${"studySessions"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all StudySessions items from collection studySessions
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export async function getAllStudySessions(filter: string = ""): Promise<StudySessionsResponse[]> {
  try {
    const results = await get("studySessions", { prompt: filter });
    return Array.isArray(results) ? results as StudySessionsResponse[] : [];
  } catch (error) {
    console.error(`Error getting StudySessions collection at path 'studySessions': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in StudySessions collection at studySessions
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export function subscribeAllStudySessions(callback: (data: StudySessionsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("studySessions", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as StudySessionsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to StudySessions collection at path '${"studySessions"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Owner only (createdBy == @user.address).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteStudySessions(sessionId: string): Promise<boolean> {
  try {
    const succeeded = await set(`studySessions/${sessionId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting StudySessions: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for StudySessions for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteStudySessions(sessionId: string): DocumentOperation {
  return { path: `studySessions/${sessionId}`, document: null };
}


/**
 * A song entry within a study session. Owner is inherited from the parent session (createdBy == @user.address). Use $entryId = songId to keep one entry per song.
 */

export interface StudySessionsSessionSongsRequest {
  songId: string;
  position: number | TimeOperation | IncrementOperation | TokenAmount;
  addedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface StudySessionsSessionSongsResponse {
  songId: string;
  position: number;
  addedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a StudySessionsSessionSongs operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildStudySessionsSessionSongs(sessionId: string, entryId: string, data: StudySessionsSessionSongsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `studySessions/${sessionId}/sessionSongs/${entryId}`, document: doc };
}

/**
 * Owner of the parent session only (session.createdBy == @user.address). songId references a song; position orders the entry; addedAt is Unix seconds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setStudySessionsSessionSongs(sessionId: string, entryId: string, data: StudySessionsSessionSongsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`studySessions/${sessionId}/sessionSongs/${entryId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting StudySessionsSessionSongs: ${formatError(error)}`);
    return false;
  }
}

export type StudySessionsSessionSongsRequestUpdate = Partial<StudySessionsSessionSongsRequest>;

/**
 * Build a StudySessionsSessionSongs update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateStudySessionsSessionSongs(sessionId: string, entryId: string, data: StudySessionsSessionSongsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `studySessions/${sessionId}/sessionSongs/${entryId}`, document: doc };
}

/**
 * Owner of the parent session only (e.g. to reorder position). (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateStudySessionsSessionSongs(sessionId: string, entryId: string, data: StudySessionsSessionSongsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`studySessions/${sessionId}/sessionSongs/${entryId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating StudySessionsSessionSongs: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Owner of the parent session only.
   (Get Single Item)
 */
export async function getStudySessionsSessionSongs(sessionId: string, entryId: string): Promise<StudySessionsSessionSongsResponse | null> {
  try {
    const result = await get(`studySessions/${sessionId}/sessionSongs/${entryId}`);
    return result as StudySessionsSessionSongsResponse | null;
  } catch (error) {
    console.error(`Error getting StudySessionsSessionSongs: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single StudySessionsSessionSongs document. (
  Read Operation Details: Owner of the parent session only.
  )
 */
export function subscribeStudySessionsSessionSongs(callback: (data: StudySessionsSessionSongsResponse | null) => void, sessionId: string, entryId: string): Promise<() => Promise<void>> {
  return subscribe(`studySessions/${sessionId}/sessionSongs/${entryId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as StudySessionsSessionSongsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to StudySessionsSessionSongs at path '${`studySessions/${sessionId}/sessionSongs/${entryId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many StudySessionsSessionSongs items from collection studySessions/${sessionId}/sessionSongs
 
  Read Operation Details: Owner of the parent session only.
  
 */
export async function getManyStudySessionsSessionSongs(sessionId: string, filter: string = ""): Promise<StudySessionsSessionSongsResponse[]> {
  try {
    const results = await get(`studySessions/${sessionId}/sessionSongs`, { prompt: filter });
    return Array.isArray(results) ? results as StudySessionsSessionSongsResponse[] : [];
  } catch (error) {
    console.error(`Error getting StudySessionsSessionSongs collection at path 'studySessions/${sessionId}/sessionSongs': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in StudySessionsSessionSongs collection at studySessions/${sessionId}/sessionSongs
 
  Read Operation Details: Owner of the parent session only.
  
 */
export function subscribeManyStudySessionsSessionSongs(callback: (data: StudySessionsSessionSongsResponse[]) => void, sessionId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`studySessions/${sessionId}/sessionSongs`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as StudySessionsSessionSongsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to StudySessionsSessionSongs collection at path '${`studySessions/${sessionId}/sessionSongs`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all StudySessionsSessionSongs items from collection studySessions/${sessionId}/sessionSongs
 
  Read Operation Details: Owner of the parent session only.
  
 */
export async function getAllStudySessionsSessionSongs(sessionId: string, filter: string = ""): Promise<StudySessionsSessionSongsResponse[]> {
  try {
    const results = await get(`studySessions/*/sessionSongs`, { prompt: filter });
    return Array.isArray(results) ? results as StudySessionsSessionSongsResponse[] : [];
  } catch (error) {
    console.error(`Error getting StudySessionsSessionSongs collection at path 'studySessions/${sessionId}/sessionSongs': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in StudySessionsSessionSongs collection at studySessions/${sessionId}/sessionSongs
 
  Read Operation Details: Owner of the parent session only.
  
 */
export function subscribeAllStudySessionsSessionSongs(callback: (data: StudySessionsSessionSongsResponse[]) => void, sessionId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`studySessions/*/sessionSongs`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as StudySessionsSessionSongsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to StudySessionsSessionSongs collection at path '${`studySessions/*/sessionSongs`}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Owner of the parent session only (removes the song from the session).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteStudySessionsSessionSongs(sessionId: string, entryId: string): Promise<boolean> {
  try {
    const succeeded = await set(`studySessions/${sessionId}/sessionSongs/${entryId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting StudySessionsSessionSongs: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for StudySessionsSessionSongs for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteStudySessionsSessionSongs(sessionId: string, entryId: string): DocumentOperation {
  return { path: `studySessions/${sessionId}/sessionSongs/${entryId}`, document: null };
}

