// Generated by TaroBase SDK Generator: 2026-07-15T16:35:00.276Z
// Collection: favorites/$favoriteId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * A favorited song for a user. Owner-scoped by userId.
 */

export interface FavoritesRequest {
  userId: AddressType;
  songId: string;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface FavoritesResponse {
  userId: string;
  songId: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Favorites operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildFavorites(favoriteId: string, data: FavoritesRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `favorites/${favoriteId}`, document: doc };
}

/**
 * Authenticated users only. userId must equal @user.address. songId references a song document. createdAt is Unix seconds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setFavorites(favoriteId: string, data: FavoritesRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`favorites/${favoriteId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Favorites: ${formatError(error)}`);
    return false;
  }
}

export type FavoritesRequestUpdate = Partial<FavoritesRequest>;

/**
 * Build a Favorites update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateFavorites(favoriteId: string, data: FavoritesRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `favorites/${favoriteId}`, document: doc };
}

/**
 * Owner only. userId cannot be reassigned to another wallet. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateFavorites(favoriteId: string, data: FavoritesRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`favorites/${favoriteId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Favorites: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Owner only (userId == @user.address).
   (Get Single Item)
 */
export async function getFavorites(favoriteId: string): Promise<FavoritesResponse | null> {
  try {
    const result = await get(`favorites/${favoriteId}`);
    return result as FavoritesResponse | null;
  } catch (error) {
    console.error(`Error getting Favorites: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Favorites document. (
  Read Operation Details: Owner only (userId == @user.address).
  )
 */
export function subscribeFavorites(callback: (data: FavoritesResponse | null) => void, favoriteId: string): Promise<() => Promise<void>> {
  return subscribe(`favorites/${favoriteId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as FavoritesResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Favorites at path '${`favorites/${favoriteId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Favorites items from collection favorites
 
  Read Operation Details: Owner only (userId == @user.address).
  
 */
export async function getManyFavorites(filter: string = ""): Promise<FavoritesResponse[]> {
  try {
    const results = await get("favorites", { prompt: filter });
    return Array.isArray(results) ? results as FavoritesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Favorites collection at path 'favorites': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Favorites collection at favorites
 
  Read Operation Details: Owner only (userId == @user.address).
  
 */
export function subscribeManyFavorites(callback: (data: FavoritesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("favorites", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FavoritesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Favorites collection at path '${"favorites"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Favorites items from collection favorites
 
  Read Operation Details: Owner only (userId == @user.address).
  
 */
export async function getAllFavorites(filter: string = ""): Promise<FavoritesResponse[]> {
  try {
    const results = await get("favorites", { prompt: filter });
    return Array.isArray(results) ? results as FavoritesResponse[] : [];
  } catch (error) {
    console.error(`Error getting Favorites collection at path 'favorites': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Favorites collection at favorites
 
  Read Operation Details: Owner only (userId == @user.address).
  
 */
export function subscribeAllFavorites(callback: (data: FavoritesResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("favorites", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as FavoritesResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Favorites collection at path '${"favorites"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Owner only (userId == @user.address).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteFavorites(favoriteId: string): Promise<boolean> {
  try {
    const succeeded = await set(`favorites/${favoriteId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Favorites: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Favorites for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteFavorites(favoriteId: string): DocumentOperation {
  return { path: `favorites/${favoriteId}`, document: null };
}

