// Generated by TaroBase SDK Generator: 2026-07-15T16:35:00.276Z
// Collection: playlists/$playlistId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * A user-created playlist. Owner-scoped by createdBy. Song membership is stored in the playlistSongs subcollection.
 */

export interface PlaylistsRequest {
  name: string;
  description?: string;
  coverUrl?: string;
  createdBy: AddressType;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PlaylistsResponse {
  name: string;
  description?: string;
  coverUrl?: string;
  createdBy: string;
  createdAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Playlists operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPlaylists(playlistId: string, data: PlaylistsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `playlists/${playlistId}`, document: doc };
}

/**
 * Authenticated users only. createdBy must equal @user.address. Add songs via the playlistSongs subcollection. createdAt is Unix seconds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPlaylists(playlistId: string, data: PlaylistsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`playlists/${playlistId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Playlists: ${formatError(error)}`);
    return false;
  }
}

export type PlaylistsRequestUpdate = Partial<PlaylistsRequest>;

/**
 * Build a Playlists update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdatePlaylists(playlistId: string, data: PlaylistsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `playlists/${playlistId}`, document: doc };
}

/**
 * Owner only. createdBy cannot be reassigned to another wallet. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updatePlaylists(playlistId: string, data: PlaylistsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`playlists/${playlistId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Playlists: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Owner only (createdBy == @user.address).
   (Get Single Item)
 */
export async function getPlaylists(playlistId: string): Promise<PlaylistsResponse | null> {
  try {
    const result = await get(`playlists/${playlistId}`);
    return result as PlaylistsResponse | null;
  } catch (error) {
    console.error(`Error getting Playlists: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Playlists document. (
  Read Operation Details: Owner only (createdBy == @user.address).
  )
 */
export function subscribePlaylists(callback: (data: PlaylistsResponse | null) => void, playlistId: string): Promise<() => Promise<void>> {
  return subscribe(`playlists/${playlistId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PlaylistsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Playlists at path '${`playlists/${playlistId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Playlists items from collection playlists
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export async function getManyPlaylists(filter: string = ""): Promise<PlaylistsResponse[]> {
  try {
    const results = await get("playlists", { prompt: filter });
    return Array.isArray(results) ? results as PlaylistsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Playlists collection at path 'playlists': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Playlists collection at playlists
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export function subscribeManyPlaylists(callback: (data: PlaylistsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("playlists", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PlaylistsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Playlists collection at path '${"playlists"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Playlists items from collection playlists
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export async function getAllPlaylists(filter: string = ""): Promise<PlaylistsResponse[]> {
  try {
    const results = await get("playlists", { prompt: filter });
    return Array.isArray(results) ? results as PlaylistsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Playlists collection at path 'playlists': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Playlists collection at playlists
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export function subscribeAllPlaylists(callback: (data: PlaylistsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("playlists", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PlaylistsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Playlists collection at path '${"playlists"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Owner only (createdBy == @user.address).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deletePlaylists(playlistId: string): Promise<boolean> {
  try {
    const succeeded = await set(`playlists/${playlistId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Playlists: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Playlists for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeletePlaylists(playlistId: string): DocumentOperation {
  return { path: `playlists/${playlistId}`, document: null };
}


/**
 * A song entry within a playlist. Owner is inherited from the parent playlist (createdBy == @user.address). Use $entryId = songId to keep one entry per song.
 */

export interface PlaylistsPlaylistSongsRequest {
  songId: string;
  position: number | TimeOperation | IncrementOperation | TokenAmount;
  addedAt: number | TimeOperation | IncrementOperation | TokenAmount;
}

export interface PlaylistsPlaylistSongsResponse {
  songId: string;
  position: number;
  addedAt: number;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a PlaylistsPlaylistSongs operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildPlaylistsPlaylistSongs(playlistId: string, entryId: string, data: PlaylistsPlaylistSongsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `playlists/${playlistId}/playlistSongs/${entryId}`, document: doc };
}

/**
 * Owner of the parent playlist only (playlist.createdBy == @user.address). songId references a song; position orders the entry; addedAt is Unix seconds. (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setPlaylistsPlaylistSongs(playlistId: string, entryId: string, data: PlaylistsPlaylistSongsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`playlists/${playlistId}/playlistSongs/${entryId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting PlaylistsPlaylistSongs: ${formatError(error)}`);
    return false;
  }
}

export type PlaylistsPlaylistSongsRequestUpdate = Partial<PlaylistsPlaylistSongsRequest>;

/**
 * Build a PlaylistsPlaylistSongs update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdatePlaylistsPlaylistSongs(playlistId: string, entryId: string, data: PlaylistsPlaylistSongsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `playlists/${playlistId}/playlistSongs/${entryId}`, document: doc };
}

/**
 * Owner of the parent playlist only (e.g. to reorder position). (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updatePlaylistsPlaylistSongs(playlistId: string, entryId: string, data: PlaylistsPlaylistSongsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`playlists/${playlistId}/playlistSongs/${entryId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating PlaylistsPlaylistSongs: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Owner of the parent playlist only.
   (Get Single Item)
 */
export async function getPlaylistsPlaylistSongs(playlistId: string, entryId: string): Promise<PlaylistsPlaylistSongsResponse | null> {
  try {
    const result = await get(`playlists/${playlistId}/playlistSongs/${entryId}`);
    return result as PlaylistsPlaylistSongsResponse | null;
  } catch (error) {
    console.error(`Error getting PlaylistsPlaylistSongs: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single PlaylistsPlaylistSongs document. (
  Read Operation Details: Owner of the parent playlist only.
  )
 */
export function subscribePlaylistsPlaylistSongs(callback: (data: PlaylistsPlaylistSongsResponse | null) => void, playlistId: string, entryId: string): Promise<() => Promise<void>> {
  return subscribe(`playlists/${playlistId}/playlistSongs/${entryId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as PlaylistsPlaylistSongsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to PlaylistsPlaylistSongs at path '${`playlists/${playlistId}/playlistSongs/${entryId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many PlaylistsPlaylistSongs items from collection playlists/${playlistId}/playlistSongs
 
  Read Operation Details: Owner of the parent playlist only.
  
 */
export async function getManyPlaylistsPlaylistSongs(playlistId: string, filter: string = ""): Promise<PlaylistsPlaylistSongsResponse[]> {
  try {
    const results = await get(`playlists/${playlistId}/playlistSongs`, { prompt: filter });
    return Array.isArray(results) ? results as PlaylistsPlaylistSongsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PlaylistsPlaylistSongs collection at path 'playlists/${playlistId}/playlistSongs': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PlaylistsPlaylistSongs collection at playlists/${playlistId}/playlistSongs
 
  Read Operation Details: Owner of the parent playlist only.
  
 */
export function subscribeManyPlaylistsPlaylistSongs(callback: (data: PlaylistsPlaylistSongsResponse[]) => void, playlistId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`playlists/${playlistId}/playlistSongs`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PlaylistsPlaylistSongsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PlaylistsPlaylistSongs collection at path '${`playlists/${playlistId}/playlistSongs`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all PlaylistsPlaylistSongs items from collection playlists/${playlistId}/playlistSongs
 
  Read Operation Details: Owner of the parent playlist only.
  
 */
export async function getAllPlaylistsPlaylistSongs(playlistId: string, filter: string = ""): Promise<PlaylistsPlaylistSongsResponse[]> {
  try {
    const results = await get(`playlists/*/playlistSongs`, { prompt: filter });
    return Array.isArray(results) ? results as PlaylistsPlaylistSongsResponse[] : [];
  } catch (error) {
    console.error(`Error getting PlaylistsPlaylistSongs collection at path 'playlists/${playlistId}/playlistSongs': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in PlaylistsPlaylistSongs collection at playlists/${playlistId}/playlistSongs
 
  Read Operation Details: Owner of the parent playlist only.
  
 */
export function subscribeAllPlaylistsPlaylistSongs(callback: (data: PlaylistsPlaylistSongsResponse[]) => void, playlistId: string, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe(`playlists/*/playlistSongs`, {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as PlaylistsPlaylistSongsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to PlaylistsPlaylistSongs collection at path '${`playlists/*/playlistSongs`}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Owner of the parent playlist only (removes the song from the playlist).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deletePlaylistsPlaylistSongs(playlistId: string, entryId: string): Promise<boolean> {
  try {
    const succeeded = await set(`playlists/${playlistId}/playlistSongs/${entryId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting PlaylistsPlaylistSongs: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for PlaylistsPlaylistSongs for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeletePlaylistsPlaylistSongs(playlistId: string, entryId: string): DocumentOperation {
  return { path: `playlists/${playlistId}/playlistSongs/${entryId}`, document: null };
}

