// Generated by TaroBase SDK Generator: 2026-07-15T16:35:00.275Z
// Collection: songs/$songId
// Edits may be overwritten by subsequent runs!

import {
  get, getMany, set, subscribe, getFiles, setFile, runQuery, count, aggregate, transformValues,
  Time, Token, Increment, Address, PublicKey,
  TimeOperation, IncrementOperation, TokenAmount, AddressType,
  TarobaseMetadata, DocumentOperation, FileItem, setMany, formatError,
} from '../db-client';
import type { AggregateResult, AggregateOperation } from '../db-client';

/**
 * An AI-generated educational song (placeholder data for MVP; generation engine deferred). Owner-scoped by createdBy.
 */

export interface SongsRequest {
  title: string;
  materialId?: string;
  genre: string;
  vocalStyle: string;
  durationSec: number | TimeOperation | IncrementOperation | TokenAmount;
  audioUrl?: string;
  lyrics?: string;
  coverUrl?: string;
  status: string;
  createdBy: AddressType;
  createdAt: number | TimeOperation | IncrementOperation | TokenAmount;
  lyricsTimestamps?: string;
  generationError?: string;
}

export interface SongsResponse {
  title: string;
  materialId?: string;
  genre: string;
  vocalStyle: string;
  durationSec: number;
  audioUrl?: string;
  lyrics?: string;
  coverUrl?: string;
  status: string;
  createdBy: string;
  createdAt: number;
  lyricsTimestamps?: string;
  generationError?: string;
  id: string;
  tarobase_created_at: number;
}

/**
 * Build a Songs operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildSongs(songId: string, data: SongsRequest): DocumentOperation {
  const doc = transformValues(data);
  return { path: `songs/${songId}`, document: doc };
}

/**
 * Authenticated users only. createdBy must equal @user.address. durationSec is required (pass 0 for placeholders). audioUrl/lyrics/coverUrl are optional placeholders. createdAt is Unix seconds. Optional: lyricsTimestamps (JSON array of {line,tSec} for synced lyrics), generationError (human-readable error message for retry UX). (Create/Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the write worked.
 */
export async function setSongs(songId: string, data: SongsRequest): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`songs/${songId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error setting Songs: ${formatError(error)}`);
    return false;
  }
}

export type SongsRequestUpdate = Partial<SongsRequest>;

/**
 * Build a Songs update operation for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildUpdateSongs(songId: string, data: SongsRequestUpdate): DocumentOperation {
  const doc = transformValues(data);
  return { path: `songs/${songId}`, document: doc };
}

/**
 * Owner only. createdBy cannot be reassigned to another wallet. lyricsTimestamps and generationError are optional and updatable by the owner. (Update Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the update worked.
 */
export async function updateSongs(songId: string, data: SongsRequestUpdate): Promise<boolean> {
  try {
    const transformedData = transformValues(data);
    const succeeded = await set(`songs/${songId}`, transformedData);
    return !!succeeded;
  } catch (error) {
    console.error(`Error updating Songs: ${formatError(error)}`);
    return false;
  }
}

/**
 * 
  Read Operation Details: Owner only (createdBy == @user.address).
   (Get Single Item)
 */
export async function getSongs(songId: string): Promise<SongsResponse | null> {
  try {
    const result = await get(`songs/${songId}`);
    return result as SongsResponse | null;
  } catch (error) {
    console.error(`Error getting Songs: ${formatError(error)}`);
    return null;
  }
}

/**
 * Subscribes to changes in a single Songs document. (
  Read Operation Details: Owner only (createdBy == @user.address).
  )
 */
export function subscribeSongs(callback: (data: SongsResponse | null) => void, songId: string): Promise<() => Promise<void>> {
  return subscribe(`songs/${songId}`, { // Use the item's basePath
    onData: (data) => {
      callback(data as SongsResponse | null);
    },
    onError: (error) => {
      console.error(`Error subscribing to Songs at path '${`songs/${songId}`}': ${formatError(error)}`);
    }
  });
}

/**
 * Get many Songs items from collection songs
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export async function getManySongs(filter: string = ""): Promise<SongsResponse[]> {
  try {
    const results = await get("songs", { prompt: filter });
    return Array.isArray(results) ? results as SongsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Songs collection at path 'songs': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Songs collection at songs
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export function subscribeManySongs(callback: (data: SongsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("songs", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Songs collection at path '${"songs"}': ${formatError(error)}`);
    }
  });
}

/**
 * Get all Songs items from collection songs
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export async function getAllSongs(filter: string = ""): Promise<SongsResponse[]> {
  try {
    const results = await get("songs", { prompt: filter });
    return Array.isArray(results) ? results as SongsResponse[] : [];
  } catch (error) {
    console.error(`Error getting Songs collection at path 'songs': ${formatError(error)}`);
    return [];
  }
}

/**
 * Subscribe to changes in Songs collection at songs
 
  Read Operation Details: Owner only (createdBy == @user.address).
  
 */
export function subscribeAllSongs(callback: (data: SongsResponse[]) => void, filter: string = ""): Promise<() => Promise<void>> {
  return subscribe("songs", {
    prompt: filter,
    onData: (data) => {
      callback(Array.isArray(data) ? data as SongsResponse[] : []);
    },
    onError: (error) => {
       console.error(`Error subscribing to Songs collection at path '${"songs"}': ${formatError(error)}`);
    }
  });
}

/**
 * 
  Delete Operation Details: Owner only (createdBy == @user.address).
   (Delete Single Item)
 * @returns A boolean indicating whether the operation succeeded (true) or failed (false). Always check this value to confirm the delete worked.
 */
export async function deleteSongs(songId: string): Promise<boolean> {
  try {
    const succeeded = await set(`songs/${songId}`, null);
    return !!succeeded;
  } catch (error) {
    console.error(`Error deleting Songs: ${formatError(error)}`);
    return false;
  }
}

/**
 * Build a delete operation for Songs for use with setMany.
 * @returns A DocumentOperation that can be passed to setMany.
 */
export function buildDeleteSongs(songId: string): DocumentOperation {
  return { path: `songs/${songId}`, document: null };
}

